default_install_hook_types:
  - pre-commit
  - commit-msg

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: local
    hooks:
      - id: commit-message-format
        name: commit message format
        entry: python3 scripts/ci/check_commit_messages.py
        language: system
        stages: [commit-msg]
