controller:
  type: daemonset
  podAnnotations:
    k8s.grafana.com/logs.job: hydrosat-alloy
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 300m
      memory: 256Mi

alloy:
  envFrom:
    - secretRef:
        name: hydrosat-grafana-cloud
  mounts:
    varlog: true
    dockercontainers: true
  configMap:
    create: true
    content: |
      discovery.kubernetes "pods" {
        role = "pod"
      }

      discovery.relabel "pods" {
        targets = discovery.kubernetes.pods.targets

        rule {
          source_labels = ["__meta_kubernetes_namespace"]
          target_label  = "namespace"
        }

        rule {
          source_labels = ["__meta_kubernetes_pod_name"]
          target_label  = "pod"
        }

        rule {
          source_labels = ["__meta_kubernetes_pod_container_name"]
          target_label  = "container"
        }

        rule {
          source_labels = ["__meta_kubernetes_pod_label_app_kubernetes_io_instance"]
          target_label  = "app_instance"
        }

        rule {
          source_labels = ["__meta_kubernetes_pod_label_app_kubernetes_io_component"]
          target_label  = "app_component"
        }
      }

      loki.source.kubernetes "pods" {
        targets    = discovery.relabel.pods.output
        forward_to = [loki.process.pods.receiver]
      }

      loki.process "pods" {
        stage.static_labels {
          values = {
            cluster = "REPLACE_WITH_CLUSTER_NAME",
          }
        }

        forward_to = [loki.write.grafana_cloud.receiver]
      }

      loki.write "grafana_cloud" {
        endpoint {
          url = sys.env("GRAFANA_CLOUD_LOKI_URL")

          basic_auth {
            username = sys.env("GRAFANA_CLOUD_LOKI_USERNAME")
            password = sys.env("GRAFANA_CLOUD_LOKI_PASSWORD")
          }
        }

        external_labels = {
          cluster = "REPLACE_WITH_CLUSTER_NAME",
        }
      }
