fullnameOverride: sight-poc-external-secrets

installCRDs: true

serviceAccount:
  create: true
  name: sight-poc-external-secrets
  annotations:
    eks.amazonaws.com/role-arn: REPLACE_WITH_EXTERNAL_SECRETS_ROLE_ARN

serviceMonitor:
  enabled: true
  namespace: monitoring

resources:
  requests:
    cpu: 50m
    memory: 128Mi
  limits:
    cpu: 250m
    memory: 256Mi
