apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: sight-poc-aws-secretsmanager
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  provider:
    aws:
      service: SecretsManager
      region: REPLACE_WITH_AWS_REGION
      auth:
        jwt:
          serviceAccountRef:
            name: sight-poc-external-secrets
            namespace: external-secrets
