apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: hydrosat-dagster-db
  namespace: dagster
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: hydrosat-aws-secretsmanager
  target:
    name: hydrosat-dagster-db
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        username: "{{ .username }}"
        password: "{{ .password }}"
        host: "hydrosat-dev-dagster.cunysm608k0x.us-east-1.rds.amazonaws.com"
        port: "5432"
        dbname: "dagster"
        url: "postgresql://{{ .username | urlquery }}:{{ .password | urlquery }}@hydrosat-dev-dagster.cunysm608k0x.us-east-1.rds.amazonaws.com:5432/dagster"
  data:
    - secretKey: username
      remoteRef:
        key: arn:aws:secretsmanager:us-east-1:564268553986:secret:rds!db-72328c75-2ddc-4eac-a815-019b55c5ab3c-NYcMyD
        property: username
    - secretKey: password
      remoteRef:
        key: arn:aws:secretsmanager:us-east-1:564268553986:secret:rds!db-72328c75-2ddc-4eac-a815-019b55c5ab3c-NYcMyD
        property: password
