apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: sight-poc-dagster-db
  namespace: dagster
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: sight-poc-aws-secretsmanager
  target:
    name: sight-poc-dagster-db
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        username: "{{ .username }}"
        password: "{{ .password }}"
        host: "REPLACE_WITH_RDS_ADDRESS"
        port: "5432"
        dbname: "dagster"
        url: "postgresql://{{ .username | urlquery }}:{{ .password | urlquery }}@REPLACE_WITH_RDS_ADDRESS:5432/dagster"
  data:
    - secretKey: username
      remoteRef:
        key: REPLACE_WITH_RDS_MASTER_SECRET_ARN
        property: username
    - secretKey: password
      remoteRef:
        key: REPLACE_WITH_RDS_MASTER_SECRET_ARN
        property: password
