apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: hydrosat-grafana-cloud
  namespace: monitoring
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: hydrosat-aws-secretsmanager
  target:
    name: hydrosat-grafana-cloud
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        GRAFANA_CLOUD_LOKI_URL: "{{ .logsUrl }}"
        GRAFANA_CLOUD_LOKI_USERNAME: "{{ .logsUsername }}"
        GRAFANA_CLOUD_LOKI_PASSWORD: "{{ .logsPassword }}"
  data:
    - secretKey: logsUrl
      remoteRef:
        key: REPLACE_WITH_GRAFANA_CLOUD_LOGS_SECRET_ARN
        property: logsUrl
    - secretKey: logsUsername
      remoteRef:
        key: REPLACE_WITH_GRAFANA_CLOUD_LOGS_SECRET_ARN
        property: logsUsername
    - secretKey: logsPassword
      remoteRef:
        key: REPLACE_WITH_GRAFANA_CLOUD_LOGS_SECRET_ARN
        property: logsPassword
