apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: hydrosat-grafana-cloud
  namespace: monitoring
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: hydrosat-aws-secretsmanager
  target:
    name: hydrosat-grafana-cloud
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        GRAFANA_CLOUD_LOKI_URL: "{{ .logsUrl }}"
        GRAFANA_CLOUD_LOKI_USERNAME: "{{ .logsUsername }}"
        GRAFANA_CLOUD_LOKI_PASSWORD: "{{ .logsPassword }}"
        GRAFANA_CLOUD_METRICS_URL: "{{ .metricsUrl }}"
        GRAFANA_CLOUD_METRICS_USERNAME: "{{ .metricsUsername }}"
        GRAFANA_CLOUD_METRICS_PASSWORD: "{{ .metricsPassword }}"
  data:
    - secretKey: logsUrl
      remoteRef:
        key: arn:aws:secretsmanager:us-east-1:564268553986:secret:hydrosat/dev/grafana-cloud-HZc1O1
        property: logsUrl
    - secretKey: logsUsername
      remoteRef:
        key: arn:aws:secretsmanager:us-east-1:564268553986:secret:hydrosat/dev/grafana-cloud-HZc1O1
        property: logsUsername
    - secretKey: logsPassword
      remoteRef:
        key: arn:aws:secretsmanager:us-east-1:564268553986:secret:hydrosat/dev/grafana-cloud-HZc1O1
        property: logsPassword
    - secretKey: metricsUrl
      remoteRef:
        key: arn:aws:secretsmanager:us-east-1:564268553986:secret:hydrosat/dev/grafana-cloud-HZc1O1
        property: metricsUrl
    - secretKey: metricsUsername
      remoteRef:
        key: arn:aws:secretsmanager:us-east-1:564268553986:secret:hydrosat/dev/grafana-cloud-HZc1O1
        property: metricsUsername
    - secretKey: metricsPassword
      remoteRef:
        key: arn:aws:secretsmanager:us-east-1:564268553986:secret:hydrosat/dev/grafana-cloud-HZc1O1
        property: metricsPassword
