apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hydrosat-external-secrets-operator
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: hydrosat-platform
  sources:
    - repoURL: https://charts.external-secrets.io
      chart: external-secrets
      targetRevision: 2.2.0
      helm:
        releaseName: hydrosat-external-secrets
        valueFiles:
          - $values/gitops/argocd/values/external-secrets-values.yaml
    - repoURL: https://github.com/BranfordTGbieor/hydrosat-infra.git
      targetRevision: dev
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: external-secrets
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
