apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sight-poc-external-secrets-resources
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: sight-poc-platform
  source:
    repoURL: REPLACE_WITH_GIT_REPOSITORY_URL
    targetRevision: REPLACE_WITH_GIT_TARGET_REVISION
    path: gitops/external-secrets
  ignoreDifferences:
    - group: external-secrets.io
      kind: ExternalSecret
      jsonPointers:
        - /status
  destination:
    server: https://kubernetes.default.svc
    namespace: external-secrets
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
