apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sight-poc-external-secrets-operator
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: sight-poc-platform
  sources:
    - repoURL: https://charts.external-secrets.io
      chart: external-secrets
      targetRevision: 2.2.0
      helm:
        releaseName: sight-poc-external-secrets
        valueFiles:
          - $values/gitops/argocd/values/external-secrets-values.yaml
    - repoURL: REPLACE_WITH_GIT_REPOSITORY_URL
      targetRevision: REPLACE_WITH_GIT_TARGET_REVISION
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: external-secrets
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
