apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: hydrosat-platform
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  description: Hydrosat data platform applications managed by Argo CD in the demo cluster
  sourceRepos:
    - https://github.com/BranfordTGbieor/hydrosat-infra.git
    - https://grafana.github.io/helm-charts
    - https://charts.external-secrets.io
  destinations:
    - namespace: dagster
      server: https://kubernetes.default.svc
    - namespace: monitoring
      server: https://kubernetes.default.svc
    - namespace: external-secrets
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
