apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sight-poc-dagster
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: sight-poc-platform
  source:
    repoURL: REPLACE_WITH_GIT_REPOSITORY_URL
    targetRevision: REPLACE_WITH_GIT_TARGET_REVISION
    path: helm/dagster
    helm:
      valueFiles:
        - values-gitops.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: dagster
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
