serviceAccount:
  annotations:
    eks.amazonaws.com/role-arn: REPLACE_WITH_DAGSTER_ROLE_ARN

image:
  repository: docker.io/gbieor/sight-poc-data
  tag: v0.2.4

dataLake:
  bucket: REPLACE_WITH_DATA_LAKE_BUCKET
  prefix: sight-poc

alerting:
  alertmanagerUrl: ""

database:
  host: REPLACE_WITH_RDS_ADDRESS
  port: 5432
  name: dagster
  username: dagster
  secretName: sight-poc-dagster-db
  createSecret: false
