serviceAccount:
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::564268553986:role/hydrosat-dev-dagster-irsa

image:
  repository: docker.io/gbieor/hydrosat-data
  tag: v0.2.4

dataLake:
  bucket: hydrosat-dev-data-lake
  prefix: hydrosat

alerting:
  alertmanagerUrl: ""

database:
  host: hydrosat-dev-dagster.cunysm608k0x.us-east-1.rds.amazonaws.com
  port: 5432
  name: dagster
  username: dagster
  secretName: hydrosat-dagster-db
  createSecret: false
