apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "sight-poc-dagster.fullname" . }}-config
data:
  dagster.yaml: |
    telemetry:
      enabled: false
    run_storage:
      module: dagster_postgres.run_storage
      class: PostgresRunStorage
      config:
        postgres_url:
          env: DAGSTER_PG_URL
    event_log_storage:
      module: dagster_postgres.event_log
      class: PostgresEventLogStorage
      config:
        postgres_url:
          env: DAGSTER_PG_URL
    schedule_storage:
      module: dagster_postgres.schedule_storage
      class: PostgresScheduleStorage
      config:
        postgres_url:
          env: DAGSTER_PG_URL
  workspace.yaml: |
    load_from:
      - grpc_server:
          host: {{ include "sight-poc-dagster.fullname" . }}-user-code
          port: {{ .Values.dagster.grpcPort }}

