{{- if .Values.database.createSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "sight-poc-dagster.databaseSecretName" . }}
type: Opaque
stringData:
  {{ .Values.database.secretKeys.username }}: {{ .Values.database.username | quote }}
  {{ .Values.database.secretKeys.password }}: {{ .Values.database.password | quote }}
  {{ .Values.database.secretKeys.url }}: {{ printf "postgresql://%s:%s@%s:%v/%s" .Values.database.username .Values.database.password .Values.database.host .Values.database.port .Values.database.name | quote }}
{{- end }}
