{{- if and .Values.dagster.userCode.podDisruptionBudget.enabled (gt (int .Values.dagster.userCode.replicaCount) 1) }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "sight-poc-dagster.fullname" . }}-user-code
spec:
  minAvailable: {{ .Values.dagster.userCode.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      app.kubernetes.io/component: user-code
      app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}
