{{- if and .Values.dagster.webserver.podDisruptionBudget.enabled (gt (int .Values.dagster.webserver.replicaCount) 1) }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "sight-poc-dagster.fullname" . }}-webserver
spec:
  minAvailable: {{ .Values.dagster.webserver.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      app.kubernetes.io/component: webserver
      app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}
